#!/bin/bash

# a simple program to generate cryptographic one-time pads
# depends on base64 and md5sum
# note that this script uses /dev/urandom as a source of random
# digits. No claims are made as to the randomness thereof.

# copyright 2013 chaz miller

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.


date=`date +%s%N`
tmpfile1=/tmp/otp1-$date
tmpfile2=/tmp/otp2-$date

base64 < /dev/urandom | sed 's/[^A-Z]//g' | tr -d '\n' | head -c 50000 > $tmpfile1

#future statistical checking of digits here

fold -50 < $tmpfile1 | awk {'print $0, " "  NR'}  > $tmpfile2

md5sum=`md5sum $tmpfile2 | sed 's/ .*//'`

cp $tmpfile2 ./OTP-md5_$md5sum

echo "file OTP-md5_$md5sum created"

head -c 100000 /dev/zero > $tmpfile1; rm $tmpfile1
head -c 100000 /dev/zero > $tmpfile2; rm $tmpfile2


